# These are supported funding model platforms

custom: ["https://www.roblox.com/games/7306710007/Epic-donation-game", "https://www.roblox.com/catalog?Category=3&Subcategory=3&CreatorName=Infinite%20Store&CreatorType=Group"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
