blank_issues_enabled: false
contact_links:
  - name: 💬 Get help
    url: https://discord.com/invite/dubhsUGcZe
    about: "If you need help with something related to Infinite Store or have a question please join our Discord server and do so in our #infinite-store or #general-dev channels."
  - name: 📚 Search for documentation
    url: https://github.com/Infinite-Store/Infinite-Store/wiki
    about: In our wiki you can find some guides and helpful tips.
