on:
  push:
    branches:
    - main

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: download-and-format
      run: |
        cargo install stylua --features luau
        stylua --verify -g '*.lua' -g '*.iy' -- .

    - uses: EndBug/add-and-commit@v9
      with:
        add: "."
        committer_name: GitHub Actions
        committer_email: actions@github.com