on:
  push:
    branches:
    - main

jobs:
  stylua:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: download-and-format
      run: |
        wget https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux.zip
        unzip stylua-linux.zip
        ./stylua --verify -g '*.luau' -- .
        rm ./stylua-linux.zip
        rm ./stylua

    - uses: EndBug/add-and-commit@v9
      if: ${{ success() || failure() }}
      with:
        add: "."
        committer_name: GitHub Actions
        committer_email: actions@github.com